DSFAAP-449: improve testing & abstract repetition
Current testing approach depends on page contents, however:

* testing doesn't capture the absence of a title prefix (since the
  Error: prefixed titles still contained the original strings, but
  aren't always appropriate)
* testing doesn't differentiate properly between headings and titles,
  since both are contained in the payload